name: Announce PR

on:
  pull_request_target:
    types: [opened]

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Announce PR
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl -H "Content-type: application/json" -X POST -d '{
            "content": "New PR #${{ env.PR_NUMBER }} *opened*:",
            "embeds": [{
              "description": "[View Pull Request](${{ env.PR_URL }})",
              "color": 3066993,
              "fields": [
                {
                  "name": "${{ env.PR_AUTHOR }}",
                  "value": "${{ env.PR_TITLE }}",
                  "inline": true
                }
              ]
            }]
          }' ${{ env.DISCORD_WEBHOOK }}
